* Stories
** Transactions table

Como um usuário do finances py, eu quero ver a lista das transações financeiras em formato de tabela.

As linhas da tabela devem ser editáveis. A UI da tabela deve exibir funções CRUD para registros.

** Importer API/UI

Como um usuário do finance spy, eu quero ser capaz de fazer upload de arquivos CSV, XML, etc. e importar com as categorias correta.

Eu devo ser capaz de editar as regras (regexes por exemplo) que associarão entradas as transações a serem importadas.

A UI deve ser capaz de exibir um diálogo em que eu posso ver como cada entrada foi classificada, de forma a permitir falhas no processo serem corrigidas.

** Dashboard Page (display)

Como um usuário do finance spy, eu devo ser capaz de visualizar minhas finanças através de dashboards e gráficos.

Os dashboards são arquivos yaml onde eu especifico as linhas, cada linha composta de gráficos, cada gráfico tem seu tipo e receita de como obter e exibir os dados.

*** Dashboard page - parameter settings

Cada página de dashboard possui opcionalmente parâmetros que permitem refinar os gráficos. Mudar os parâmetro modifica os gráficos reativamente.

A UI deve ser concisa e não deve poluir a página dos gráficos.

